#!/usr/bin/env python3
"""Wrap .iLogicVb rule files so a real VB compiler can type-check them.

iLogic takes a rule's top-level statements and puts them in a method, then
hoists any trailing Sub/Function declarations to class scope. This reproduces
that transform so the rule text that ships is exactly the rule text compiled.
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
RULES_DIR = os.path.join(HERE, "..", "..", "ilogic")
OUT_DIR = os.path.join(HERE, "generated")

DECL = re.compile(r'^(Public\s+|Private\s+|Friend\s+)?(Sub|Function)\s+\w+', re.IGNORECASE)

def wrap(path):
    name = os.path.splitext(os.path.basename(path))[0]
    mod = re.sub(r'\W', '_', name)
    lines = open(path, encoding='utf-8').read().splitlines()

    body, decls, in_decls = [], [], False
    for ln in lines:
        # AddVbFile is an iLogic pre-compile directive; the project references
        # the same engine files directly instead.
        if ln.strip().lower().startswith('addvbfile'):
            continue
        if not in_decls and DECL.match(ln) and not ln.startswith((' ', '\t')):
            in_decls = True
        (decls if in_decls else body).append(ln)

    out = [
        "' AUTO-GENERATED by wrap_rules.py from ilogic/%s -- do not edit." % os.path.basename(path),
        "' Compile-check scaffolding only; never deployed.",
        "Option Strict Off",
        "Option Explicit On",
        "",
        "Imports System",
        "Imports System.Collections.Generic",
        "Imports System.Globalization",
        "Imports System.IO",
        "Imports Inventor",
        "",
        "Module %s" % mod,
        "    Sub RuleBody()",
    ]
    out += ["        " + l if l.strip() else "" for l in body]
    out += ["    End Sub", ""]
    out += decls
    out += ["End Module"]

    os.makedirs(OUT_DIR, exist_ok=True)
    dst = os.path.join(OUT_DIR, mod + ".g.vb")
    open(dst, 'w', encoding='utf-8').write("\n".join(out) + "\n")
    return dst

if __name__ == "__main__":
    for f in sorted(os.listdir(RULES_DIR)):
        if f.endswith(".iLogicVb"):
            print("wrapped", os.path.relpath(wrap(os.path.join(RULES_DIR, f)), HERE))
