#!/usr/bin/env python3
"""Wrap .iLogicVb rule files so a real VB compiler can type-check them.

Also enforces iLogic's program-format rule, which is not a style preference:

    As soon as a rule declares any Sub or Function of its own, iLogic stops
    auto-wrapping loose statements and REQUIRES an explicit Sub Main() as the
    entry point. Without it the rule editor refuses to compile with
    "Error in rule program format: The rule must contain: Sub Main() ... End Sub"

Because that check happens inside Inventor's rule editor, a plain VB compiler
will happily build a rule that iLogic then rejects. So we assert it here.
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
RULES_DIR = os.path.join(HERE, "..", "..", "ilogic")
OUT_DIR = os.path.join(HERE, "generated")

DECL = re.compile(r'^(Sub|Function)\s+(\w+)', re.IGNORECASE)
MAIN = re.compile(r'^Sub\s+Main\s*\(\s*\)\s*$', re.IGNORECASE)

problems = []


def wrap(path):
    fname = os.path.basename(path)
    name = os.path.splitext(fname)[0]
    mod = re.sub(r'\W', '_', name)
    lines = open(path, encoding='utf-8').read().splitlines()

    # AddVbFile is an iLogic pre-compile directive; the project references the
    # same engine files directly instead.
    body = [l for l in lines if not l.strip().lower().startswith('addvbfile')]

    decls = [(i, m.group(2)) for i, l in enumerate(body) for m in [DECL.match(l)] if m]
    has_main = any(MAIN.match(l) for l in body)

    if decls and not has_main:
        problems.append(
            "%s declares %s at rule scope but has no 'Sub Main()'. iLogic will "
            "reject it with \"The rule must contain: Sub Main() ... End Sub\"."
            % (fname, ", ".join(n for _, n in decls[:3])))
    if has_main:
        first = decls[0][1] if decls else None
        if first is not None and first.lower() != "main":
            problems.append(
                "%s: 'Sub Main()' must be the FIRST declaration; found '%s' before it."
                % (fname, first))

    # Rename the entry point so two rule modules can coexist in one assembly.
    body = [re.sub(r'^Sub\s+Main\s*\(\s*\)\s*$', 'Sub RuleEntryPoint()', l) for l in body]

    out = [
        "' AUTO-GENERATED by wrap_rules.py from ilogic/%s -- do not edit." % fname,
        "' Compile-check scaffolding only; never deployed.",
        "' Sub Main() is renamed RuleEntryPoint() so both rule modules can coexist.",
        "Option Strict Off",
        "Option Explicit On",
        "",
        "Imports System",
        "Imports System.Collections.Generic",
        "Imports System.Globalization",
        "Imports System.IO",
        "Imports Inventor",
        "",
        "Module %s" % mod,
    ]
    out += body
    out += ["End Module"]

    os.makedirs(OUT_DIR, exist_ok=True)
    dst = os.path.join(OUT_DIR, mod + ".g.vb")
    open(dst, 'w', encoding='utf-8').write("\n".join(out) + "\n")
    return dst


if __name__ == "__main__":
    for f in sorted(os.listdir(RULES_DIR)):
        if f.endswith(".iLogicVb"):
            print("wrapped", os.path.relpath(wrap(os.path.join(RULES_DIR, f)), HERE))
    for p in problems:
        print("  PROBLEM  " + p)
    sys.exit(1 if problems else 0)
